### ISSUE TITLE
Objective C example not available

### ISSUE THREAD

**Issue by amitanmol** [onehub/api-examples#1]
Hi Team,

I am an iOS developer, I tried all the mentioned example code at http://developer.onehub.com/authorization/, and https://oauth.net/code/ location to get access token from OneHub using Objective C, but could not get exact implementation for that. I also did google for same but no more help. 

So, I written example code to get access token from OneHub in Objective C and got the access token successfully. I thought it can help others so I shared it on github. Please find repository at https://github.com/amitanmol/OneHubOAuth location.

I am also working on its library in Objective C using OneHub REST API. I will share that also, so other iOS or macOS developers can get benefitted to access OneHub in their apps.

Thanks
Amit

**Comment by WanderingMatt** [comment]
@amitanmol Awesome! Thanks for showing your work on this. We may consider adding this to our list of examples in the future, provided:

- It is structured more like a library (or even a CocoaPod) that could be added globally to an app
- It comes in the form of a Pull Request

Cheers!
